---
type: object
properties:
  nodejs:
    description: NodeJS namespace
    type: object
    properties:
      package.json:
        type: object
        properties:
          name:
            description: The name of the package.
            type: string
            maxLength: 214
            minLength: 1
            pattern: "^(?:@(?:[a-z0-9-*~][a-z0-9-*._~]*)?/)?[a-z0-9-~][a-z0-9-._~]*$"
          version:
            description: Version must be parseable by node-semver, which is bundled
              with npm as a dependency.
            type: string
          description:
            description: This helps people discover your package, as it's listed in
              'npm search'.
            type: string
          keywords:
            description: This helps people discover your package as it's listed in
              'npm search'.
            type: array
            items:
              type: string
          main:
            description: The main field is a module ID that is the primary entry point
              to your program.
            type: string
          scripts:
            description: The 'scripts' member is an object hash of script commands
              that are run at various times in the lifecycle of your package. The
              key is the lifecycle event, and the value is the command to run at that
              point.
            type: object
            additionalProperties:
              type: string
          dependencies:
            description: Dependencies are specified with a simple hash of package
              name to version range. The version range is a string which has one or
              more space-separated descriptors. Dependencies can also be identified
              with a tarball or git URL.
            type: object
            additionalProperties:
              type: string
          devDependencies:
            description: Dependencies are specified with a simple hash of package
              name to version range. The version range is a string which has one or
              more space-separated descriptors. Dependencies can also be identified
              with a tarball or git URL.
            type: object
            additionalProperties:
              type: string
      version:
        description: NodeJS version
        type: number
        enum:
        - 20
        - 18
        - 16
      command:
        description: Command to start application
        type: string
    required:
    - package.json
    - version
    - command
required:
- nodejs
