---
"$schema": http://json-schema.org/draft-07/schema#
title: Website
type: object
properties:
  ngc_website_title:
    type: string
  ngc_website_description:
    type: string
  ngc_website_keywords:
    type: array
    items:
      type: string
required:
- ngc_website_title
- ngc_website_description
- ngc_website_keywords
